// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncamcpulujvwpdmszbmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jYW1jcHVsdWp2d3BkbXN6Ym1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzk0MTksImV4cCI6MjA3MjY1NTQxOX0.YgnNSZtHIKKK8K-ZIdGly3YxL_SmGkKXtbDiMiOMyrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});